### ISSUE TITLE
[BUG] Card sorting is broken

### ISSUE THREAD

**Issue by ghost** [SillyTavern/SillyTavern#1069]
> **Warning**. Complete **all** the fields below. Otherwise, your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
I usually sort my cards by the newest, but it's not doing that for me. It seems to be sorting it by recent instead as it keeps pushing the character I am chatting with to the top.
I have not edited the card in anyway, I would understand this behavior if I had.

**To Reproduce**
1. Go to select character
2. Sort by "Newest"
3. Chat with character that isn't that new
4. Character will appear at the top of the character list even though it should not.

**Expected behavior**
It should sort the character by the date it was added, not when it was used.

**Screenshots**
I think it should be fairly explanatory but I will add them if needed.

**Desktop (please complete the following information):**
 - OS/Device: Windows 11
 - Environment: Local with extras
 - Node.js version (if applicable): 18.17.0
 - Browser: Waterfox (Basically just Firefox)
 - Generation API: oobabooga
 - Branch release
 - Model TheBloke_MythoMax-L2-13B-GPTQ

**Additional context**
This happened after recent update, I launch SillyTavern through the UpdateAndStart.bat so this bug has appeared within last 24 hours or so.

**Comment by Cohee1207** [comment]
I managed to reproduce it. The issue is that the atomic file writing resets the creation date on updating the character. I'm currently looking for a solution.

**Comment by ghost** [comment]
Okay cool. I hope you will find the solution, good luck

**Comment by Cohee1207** [comment]
I can propose the following: abandon the sorting by file creation date and sort by internal card creation date field. The only problem is that this field wasn't set for v2 format cards previously (which means that the original import date is lost). That means that such cards you've previously imported will be sorted on top after the update, but they will no longer hoist on doing updates to them. If that's okay for you, I can implement that.

**Comment by ghost** [comment]
Yeah, that's completely fine. I just prefer the cards stays in order in I want them to be in even if it means having the order to be messed up one more time for it to happen.

**Comment by Cohee1207** [comment]
The fix has been pushed to staging. If you have the ability to switch branches and test - that would be appreciated.

**Comment by ghost** [comment]
Yeah, I'm able to switch easily. I've done the initial testing of it and it does seem to work like it should now. Although probably should do bit more testing before I can safely confirm.

**Comment by ghost** [comment]
It's still broken. I think it will be bit harder to reproduce because I'm not sure when or how it happens, but the whole list completely refreshes itself and the order gets completely changed. I know page refreshing at least can cause it happen, but there seems to be more than just that, that does it.

**Comment by Cohee1207** [comment]
How many v2 cards have you previously imported?

**Comment by ghost** [comment]
I'm not sure how to differentiate between the version of the cards but there is probably quite a few of them.

**Comment by Cohee1207** [comment]
The fix incorporates this logic: either use the embedded creation date if available, or fallback to the file date as before. Is there anything between the cards that change their position? Were they updated previously by you or they are intact since being imported? And are the cards that are getting updated keep their position on refresh? Every bit of information can help.

**Comment by ghost** [comment]
I can't say for sure because after I pick up a card, chat with the bot for while, refresh the page, it has pushed some of the cards randomly to be the newest. There isn't really any rhyme or reason for it.
I haven't updated the cards in any way after downloading and adding them to the UI and even if I had, it has pushed cards to the top I have not used before or it has been very long time I've used them.

It does sound like a nuisance to figure out so if it can't be fixed, it's fine. Hopefully someone else is able to figure out it better what triggers it as I have no clue at all what might be the cause.

**Comment by Cohee1207** [comment]
Got my hands on an install with a greater number of v2 cards and hopefully fixed it now (staging)

**Comment by ethicalresearch** [comment]
I have a similiar bug
only happens if you change the order settings from whatever to > newest
it mess up the order, if you add a new card that card goes below others and not into the first slot as always
updating to the last branch fix it but it appear again (edit)

**Comment by Kingmiami** [comment]
Still broken in my experience.

**Comment by Omniphantasm** [comment]
Still busted here too.

**Comment by Cohee1207** [comment]
Missing create_date in metadata should now correctly use the file creation date instead of the current date which caused misplaced bots in the newest sorting.

**Comment by gipppp** [comment]
The sorting was still broken for me. Some cards were placed correctly, some weren’t. I found out that it was caused by a few old cards. They have a ‘create_date’ field in Unix timestamp format, but the type is a string.
https://github.com/SillyTavern/SillyTavern/blob/f05d90bada1434fc540b733a6e04f231ed54ec3e/public/scripts/utils.js#L643
parseTimestamp function here doesn't cover this case. The code below fixes the problem for me.
```js
    // Unix time (legacy TAI / tags)
    if (typeof timestamp === 'number' || /^\d*$/.test(timestamp)) {
        if (isNaN(timestamp) || !isFinite(timestamp) || timestamp < 0) {
            return moment.invalid();
        }
        return moment(Number(timestamp));
    }
```
