### ISSUE TITLE
[BUG] Uploading multiple character cards only imports the tags from the last one

### ISSUE THREAD

**Issue by Oninaig** [SillyTavern/SillyTavern#1250]
### Environment

Self-Hosted (Bare Metal)

### System

Ubuntu 20.04 all browsers

### Version

SillyTavern 1.10.4 'release' (df55a661)

### Describe the problem

When uploading multiple characters, only the tags from the last character imported are actually imported. This is because of lines 228-232 here: https://github.com/SillyTavern/SillyTavern/blob/release/public/scripts/tags.js#L228

If you remove those lines and disable the popup, all tags from _all_ character cards uploaded are added to their respective card(s).

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Fixed, verified.

**Comment by Silhygames** [comment]
For the record, this is still an issue as of V:1.11.6. It has not been fixed.
