### ISSUE TITLE
[FEATURE_REQUEST] Add 'formality' header to POST /v2/translate endpoint (Deepl API)

### ISSUE THREAD

**Issue by heyFlorentin** [SillyTavern/SillyTavern#1405]
### Describe the solution you'd like

Currently, when using the Deepl API to translate text, there is no option to specify the level of formality in the translated output. This becomes a significant issue when translating languages like German (DE), French (FR), Italian (IT), and others, as there can be substantial differences in language formality.

### Describe alternatives you've considered

I suggest adding the 'formality' header to the POST /v2/translate endpoint in the Deepl API to address this. This header would allow users to indicate the desired level of formality for the translation.

**Comment by Cohee1207** [comment]
Added a config.yaml value for the formality value. I don't have a DeepL API key, so I kindly ask you to test this in the staging branch.

1. git pull
2. npm install
3. Edit config.yaml and set `deepl.formality` to one of the following: default, more, less, prefer_more, prefer_less
4. Do a DeepL request and observe the results

**Comment by heyFlorentin** [comment]
I can successfully translate messages using the _translate message_ button within the chat, but it fails to translate inputs with `DeepL error:  Bad Request`when using **Auto-mode**.

<img width="422" alt="Screenshot" src="https://github.com/SillyTavern/SillyTavern/assets/118486333/e5bcb283-98f8-458f-8f2e-c80c20d3b520">

----

```
Input text: Write me a personalized GitHub Tutorial about any topic.
DeepL error:  Bad Request {"message":"'formality' is not supported for given 'target_lang'."}
{
  prompt: '[Coding Sensei = assists User with coding-related questions, and provides example codes within markdown codeblocks.]\n' +
    '***\n' +
    'User: \n' +
    'Coding Sensei:',
  params: {
    gui_settings: false,
    sampler_order: [
      6, 0, 1, 2,
      3, 4, 5
    ],
    max_context_length: 2048,
    max_length: 250,
    rep_pen: 1.1,
    rep_pen_range: 600,
    rep_pen_slope: 0,
    temperature: 1,
    tfs: 1,
    top_a: 0,
    top_k: 0,
    top_p: 0.95,
    min_p: 0,
    typical: 1,
    s1: 6,
    s2: 0,
    s3: 1,
    s4: 2,
    s5: 3,
    s6: 4,
    s7: 5,
    use_world_info: false,
    singleline: false,
    stop_sequence: [ '\nUser:', '\n***' ],
    streaming: false,
    can_abort: false,
    mirostat: 0,
    mirostat_tau: 5,
    mirostat_eta: 0.1,
    use_default_badwordsids: false,
    grammar: '',
    api_server: 'http://127.0.0.1:5000/api',
    main_api: 'koboldhorde',
    n: 1,
    frmtadsnsp: false,
    frmtrmblln: false,
    frmtrmspch: false,
    frmttriminc: false
  },
  trusted_workers: false,
  models: [ 'aphrodite/Sao10K/Stheno-v2-Delta-AWQ' ]
}
Input text: I'm here to help you with any questions or problems you have related to coding. Please provide the specific language or topic you need assistance with, and feel free to include your code for review or ask a question about syntax, functionality, best practices, or guidance on how to approach a problem.


For now, let me know if there's anything in particular you want to discuss or learn about.
Translated text: Ich bin hier, um dir bei allen Fragen oder Problemen zu helfen, die du mit dem Programmieren hast. Bitte gib die Sprache oder das Thema an, zu der/dem du Hilfe brauchst, und schicke mir deinen Code zur Überprüfung oder stelle mir eine Frage zu Syntax, Funktionalität, Best Practices oder zur Vorgehensweise bei einem Problem.


Lass mich wissen, wenn du etwas Bestimmtes besprechen oder lernen möchtest.
```

**Comment by Cohee1207** [comment]
I wish DeepL would just silently ignore formality for unsupported languages, but it decided to go nuts with the validation...

**Comment by Cohee1207** [comment]
Should be fixed now, I hope.

**Comment by heyFlorentin** [comment]
The Input still doesn't seem to work with Auto-mode enabled, but now I don't receive an Error message.
I appreciate your effort so far!

---

Input
```bash
Input text: Your task is to write an "Hello World" script using Python.
Translated text: Your task is to write an "Hello World" script using Python.
````
Response
```bash
Input text: Sure! To create a simple "Hello World" script in Python, you can use a text editor or an IDE (Integrated Development Environment) like Python IDLE or Visual Studio Code. First, make sure you have Python installed on your system. You can download it from [Python official website](https://www.python.org/downloads/). [...]
Translated text: Klar! Um ein einfaches "Hello World"-Skript in Python zu erstellen, kannst du einen Texteditor oder eine IDE (Integrated Development Environment) wie Python IDLE oder Visual Studio Code verwenden. Stelle zunächst sicher, dass du Python auf deinem System installiert hast. Du kannst es von der [offiziellen Python-Website](https://www.python.org/downloads/) herunterladen. [...]
```
![SillyTavern](https://github.com/SillyTavern/SillyTavern/assets/118486333/80a128dc-550e-4f66-8f0a-0081a02dc056)

**Comment by Cohee1207** [comment]
Auto-mode for input works by translating your input into English as internal text but displaying input in your original language. I see you already input English text, so it works exactly as expected.

**Comment by heyFlorentin** [comment]
Oh yeah, you're right! Excuse my oversight and see this issue as resolved. Much appreciation!
