### ISSUE TITLE
[BUG] Character Expressions sprite upload does not update thumbnail

### ISSUE THREAD

**Issue by Technologicat** [SillyTavern/SillyTavern#1720]
### Environment

Self-Hosted (Bare Metal)

### System

Firefox 121.0, Linux Mint 21.1

### Version

1.11.2 'staging' (e9a7be5)

### Desktop Information

Node.js: v20.10.0
API: oobabooga (self-hosted / bare metal), with the OAI compatible endpoints
Branch: staging
Model: [dolphin-2.6-mistral-7b-dpo-laser.Q5_K_M.gguf](https://huggingface.co/TheBloke/dolphin-2.6-mistral-7B-dpo-laser-GGUF)

### Describe the problem

**Steps to reproduce**

- Open the Extensions ⊳ Character Expressions panel
- Click on the up-arrow ("Upload image" button) on an emotion slot to upload a new sprite
- Browse for file, click ok

**Expected result**

The thumbnail updates with the thumbnail of the new sprite.

**Actual result**

The thumbnail does not update.

### Additional info

Encountered during `talkinghead` testing, when frequently uploading different `talkinghead` sprites to test them using the same character.

*Upload sprite pack* might have the same issue, too - I haven't tried that feature.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Done.

**Comment by Technologicat** [comment]
Tested (b2509f8d). Uploading a new `talkinghead.png` by clicking the "Upload image" button for that individual sprite slot still doesn't update the thumbnail for me.

**Comment by Cohee1207** [comment]
Firefox has a very aggressive image cache which doesn't bust when using Fetch API with `no-cache`. Using a query string trick will cause a heavy network load on every chat load.

**Comment by Technologicat** [comment]
I agree that if Firefox chooses not to respect `no-cache`, then it's the job of the Firefox devs to fix that, not for apps to work around it.

I didn't realize Firefox was so borked. Might be useful to warn others in the README?

Confirmed working in Chromium, Version 120.0.6099.109 (Official Build) for Linux Mint (64-bit).

The *Extensions* settings page scrolls back to the beginning when it refreshes, and Chromium doesn't remember the last directory I've uploaded a file from, but other than that, it's now behaving as expected.
