### ISSUE TITLE
[FEATURE_REQUEST] Persona sorting

### ISSUE THREAD

**Issue by CounterfeitMonk** [SillyTavern/SillyTavern#1775]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I like the new Persona Management design, but I'm confused how the personas are sorted, they seem to be almost random as far as I can tell.

### Describe the solution you'd like

 Can we have sort options for personas like we do for bots? Or the ability to custom-sort our personas? I have certain personas I use more than others and I'd like the ability to have them be at the top, for example.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
I can only offer alphabetical sorting. Other types are likely not possible due to lacking metadata.

**Comment by CounterfeitMonk** [comment]
I would be happy with that, it's still a more consistent sorting method and I can work with that!

**Comment by Cohee1207** [comment]
Done
https://github.com/SillyTavern/SillyTavern/commit/a746077a1e1666290b32f901772ec18ef811abc6

**Comment by CounterfeitMonk** [comment]
That didn't seem to fix the sorting. I see the `A-Z` dropdown, but either way I sort (A-Z or Z-A), they're still not in alphabetical order (though they do have some sort of internal sorting). Is this something where I'd need to re-make my personas to take effect with the new sorting order?
 
Screenshots attached, as example. (don't judge my stupid personas 😅)


![persona_A-Z](https://github.com/SillyTavern/SillyTavern/assets/147885913/c4ef0226-4cd9-469a-8c8f-60de5e9d5660) ![persona_Z-A](https://github.com/SillyTavern/SillyTavern/assets/147885913/1b6b2501-b44b-489f-9358-41abfcedc2f8)

**Comment by Cohee1207** [comment]
Oh yeah, I didn't realize it was sorting by ID instead of name.

**Comment by CounterfeitMonk** [comment]
That fixed it, thanks for the quick fix, Cohee!
