### ISSUE TITLE
[BUG] "Unlocked" checkbox is unchecked when updating preset

### ISSUE THREAD

**Issue by p-e-w** [SillyTavern/SillyTavern#1920]
### Environment

Self-Hosted (Bare Metal)

### System

Firefox 123.0, Ubuntu 22.04

### Version

1.11.3

### Describe the problem

1. Select a preset.
2. Check the "Unlocked" checkbox to unlock the context size.
3. Click "Update current preset".

The "Unlocked" checkbox is magically unchecked.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
This should be fixed already (but not yet released): https://github.com/SillyTavern/SillyTavern/pull/1909

**Comment by Wolfsblvt** [comment]
Release **1.11.7** is out with this fix included.

**Comment by p-e-w** [comment]
@Cohee1207

Reopening, as this bug is still present even in 1.11.8.

**Comment by Cohee1207** [comment]
The unlock is not saved if the context size chosen does not exceed the unlock threshold (2k response, 8k context).
