### ISSUE TITLE
[BUG] MUI Preset is not applied on startup

### ISSUE THREAD

**Issue by bobcate** [SillyTavern/SillyTavern#2274]
### Environment

🪟 Windows

### System

Thorium v123.0.6312.133, OperaGX v109.0.5097.93, Firefox v126.0

### Version

1.11.8 'release' (204a9345), 1.12.0 'release' (884f2692)

### Describe the problem

I have saved a preset for the moving UI. It is listed under the `MUI Preset` in `User Settings`. It works fine.
The problem is, when I first connect to ST or refresh the browser page, the MUI preset resets to `Default` "visually". I can still see my custom preset is selected.
So, I have to manually switch to default and back to my custom preset everytime i start ST or refresh the browser page.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Can't reproduce. It stays selected even if I refresh the page or switch browsers. Check DevTools for errors, please.

**Comment by bobcate** [comment]
No errors in the console. I deleted the default preset and it still resets to default positions
To clarify, custom preset does stay selected but the custom positions of windows doesn't apply unless I switch to and from another preset.

**Comment by bobcate** [comment]
In `power-user.js`: ![Untitled](https://github.com/SillyTavern/SillyTavern/assets/34423403/0f8f7caf-a567-477e-b338-ce2ac877df01)

I'm not even sure if this is the code that loads the preset on launch/refresh, but I added some logging to see if they showed up in the console(i set it to verbose).
And only the ones marked green showed up. So is the preset not loading?

Edit: I fiddled around more but couldn't find anything useful. Updated to v1.12.0, still the same.
Could you tell me what can I do to force apply my preset on load?

**Comment by RossAscends** [comment]
This is hopefully fixed by commit: 
https://github.com/SillyTavern/SillyTavern/commit/863e0c3643a60f519a9de85484e1fc5023584295

**Comment by bobcate** [comment]
Bug is still present but its behavior changed.
I pulled staging, loaded ST, selected my preset, it works. Here's what happens after:

On the first refresh of the page:
- My already open and locked `AI Response Configuration` and `Character Management` windows get closed, but their custom sizes are saved.
- Character expression window position resets.
- Main chat window position is saved correctly.
- 2 popups say: `Panel positions reset due to zoom/resize.`
- Browser log ![Untitled](https://github.com/SillyTavern/SillyTavern/assets/34423403/008cd98d-b851-4541-9522-9666e8328ac9)


And on the second refresh, it's the same as the original bug: MUI resets completely, everything is default.
- Browser log  ![Untitled](https://github.com/SillyTavern/SillyTavern/assets/34423403/fb24461d-4be6-453c-a4d7-c8995215ea9c)

**Comment by bobcate** [comment]
Bug is fixed with https://github.com/SillyTavern/SillyTavern/commit/9b1a254553ee4557b919121ed76a48a09292c839
