### ISSUE TITLE
[BUG] iOS and iPad issues

### ISSUE THREAD

**Issue by SimplyCorbett** [SillyTavern/SillyTavern#3050]
### Environment

🍎 Mac

### System

Safari, 18.1 (latest iOS and iPadOS)

### Version

1.12.7

### Describe the problem

On iPadOS with safari half the chat cuts off and the send button is missing.

On the iPhone with safari the website looks normal (for a mobile site) but the send button is entirely missing (the airplane).

If I use Firefox with iPadOS everything works, but it doesn't look that great either - some UI issues overall.

I have not tried Firefox on iOS but I assume that would also fix the problem.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Send button is missing if you're not connected to any of the backend APIs.

**Comment by SimplyCorbett** [comment]
Hi,

You’re correct!

There are still issues with ipados and safari though, especially in settings menus.

See attached image (half the settings menu is off screen and cannot be scrolled to).

![IMG_0061](https://github.com/user-attachments/assets/85816361-e8b2-4daa-b74c-46238567e088)

**Comment by Zilong-L** [comment]
should be closed since the issue is resolved.

**Comment by TheBra1nz** [comment]
This is still an issue as of iPadOS 26.5 (latest) and SillyTavern 1.18.0 (latest).

<img width="3200" height="2229" alt="Image" src="https://github.com/user-attachments/assets/28d0533e-9569-45bc-af58-2f1970142261" />

**Comment by frenzybiscuit** [comment]
Using the ipad at all is pain with sillytavern.

Especially when using an external monitor :/
