### ISSUE TITLE
[FEATURE_REQUEST] Include Custom Stopping Strings in Connection Profiles, Advanced Formatting exports

### ISSUE THREAD

**Issue by AquaSZS** [SillyTavern/SillyTavern#3365]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Different models/presets may require different Custom Stopping Strings (e.g. `<|...|>` unique to Llama models), but as of 1.12.11, neither Connection Profiles nor Advanced Formatting master export saves this setting. I was especially surprised that Formatting export didn't include this setting, because the UI strongly suggests Custom Stopping Strings should be a part of it.

### Describe the solution you'd like

Include Custom Stopping Strings in Advanced Formatting master export and Connection Profiles. This would not only make switching everything a 1-click process but also help people share this setting more easily.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
Done in staging. Go test it if you want.

**Comment by AquaSZS** [comment]
Connection profiles are saving this setting properly! Advanced Formatting master export still doesn't include the stopping strings, but #1832 might be about that.
