### ISSUE TITLE
[BUG] Token Probabilities — KoboldCPP

### ISSUE THREAD

**Issue by Vhallo** [SillyTavern/SillyTavern#4658]
### Environment

🪟 Windows

### System

KoboldCPP

### Version

1.13.4

### Describe the problem

When using TabbyAPI, Token Probabilities work whether Streaming is enabled or not. However, with KoboldCPP it seems to only work when Streaming is disabled?

Is that a SillyTavern bug, or a limitation of KoboldCPP?

### Please tick the boxes

- [x] I have explained the issue clearly, and I included all relevant info
- [x] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [x] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)
- [x] I confirm that my issue is not related to third-party content, unofficial extension or patch. If in doubt, check with a new [user account](https://docs.sillytavern.app/administration/multi-user/) and with extensions disabled

**Comment by Vhallo** [comment]
So, I checked into it, and it's a limitation of SillyTavern. Token Probabilities work fine in Kobold's basic UI, both with streaming and without.

**Comment by Vhallo** [comment]
Btw, you can still get the Token Probabilities after streaming from Kobold via api/extra/last_logprobs, then parse them normally with parseOpenAIChatLogprobs.

**Comment by LostRuins** [comment]
For streaming, currently koboldcpp does not send logprobs. This will be changed in the next version, after which Chat Completions logprobs should work immediately. 

For completions api, @Cohee1207 will need to add a small change to get logprobs streaming from kcpp to work as well.

**Comment by Vhallo** [comment]
Has this been looked into since? Seems that even with ST 1.15 + Kobold 1.105.1, the logprobs still don't work, unless I hack them in manually via: "api/extra/last_logprobs"

**Comment by LostRuins** [comment]
should be working, koboldcpp is definitely sending logprobs now at the end of the response if requested

**Comment by Vhallo** [comment]
Checked into it, and only Text Completion with streaming turned on still fails. But yes, it does work with Chat Completion now, so should be ready when it comes to koboldcpp. @Cohee1207
