### ISSUE TITLE
[Feature Request] "Start reply with" char only checkbox

### ISSUE THREAD

**Issue by IkariDevGIT** [SillyTavern/SillyTavern#703]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
I find it annoying if i do something like "<{{char}}'s thoughts: ", and i click impersonate it also adds it onto my character which destroys my impersonation

**Describe the solution you'd like**
In would like a check box or something like that, that makes "start reply with" only active on the reply of the character

**Describe alternatives you've considered**
cant think of any alternatives

**Additional context**
---

**Comment by alicat22** [comment]
This was fixed in an early dev commit. Please pull again. `Start Reply With` should not be prepended on `Impersonate`.

**Comment by IkariDevGIT** [comment]
d5c816ed2bac09d33900d292e7b19c9aed308d38 (newest as of now) dev branch, still not working
