### ISSUE TITLE
[BUG] NovelAI context sizes for tiers are wrong

### ISSUE THREAD

**Issue by minipasila** [SillyTavern/SillyTavern#924]
> **Warning**. Complete **all** the fields below. Otherwise, your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
It seems to have hard coded maximum tokens for different tiers. For example Scroll tier seems to have a maximum of 2048 tokens even though those maximum tokens have changed to 6144 for the new Kayra model and for Clio it's 8192 tokens. The preset's own maximum context also is being ignored due to that.

**To Reproduce**
1. Connect to NovelAI API.
2. Select Kayra (with Scroll tier).
3. Try to continue a conversation with more than 2048 tokens.
4. Check the commandline/console for the logs which will show that it has truncated the conversation to be under 2048 tokens.

**Expected behavior**
When you have a Scroll tier you should have 6144 context length for Kayra and for Clio it's changed to 8192 for all tiers.
Other tiers are the following:
Tablet: Clio 8192, Kayra 3072
Scroll: Clio 8192, Kayra 6144
Opus: Clio 8192, Kayra 8192

**Screenshots**
![image](https://github.com/SillyTavern/SillyTavern/assets/4912958/da5bedc5-9d21-4941-b386-8c2ef4262101)

**Logs**

```
Event emitted: message_swiped [eventemitter.js:52:13](http://127.0.0.1:8000/scripts/eventemitter.js)
caught here 2 [script.js:6768:45](http://127.0.0.1:8000/script.js)
NovelAI subscription limit reached. Max context size is now 2048 [script.js:3186:21](http://127.0.0.1:8000/script.js)
Randomizer skipped: disabled. [index.js:41:17](http://127.0.0.1:8000/scripts/extensions/randomize/index.js)
Core/all messages: 8/9 [script.js:2374:17](http://127.0.0.1:8000/script.js)

    setFloatingPrompt entered
    ------
    lastMessageNumber = 4
    metadata_keys.interval = 1
    [authors-note.js:270:13](http://127.0.0.1:8000/scripts/authors-note.js)
Context size: 1748; WI budget: 437 (max% = 25%, cap = 0) [world-info.js:953:13](http://127.0.0.1:8000/scripts/world-info.js)
Global world info has 0 entries [world-info.js:894:13](http://127.0.0.1:8000/scripts/world-info.js)
Character jREG's base world could not be found or is empty! Skipping... [world-info.js:855:17](http://127.0.0.1:8000/scripts/world-info.js)
WI using char first [world-info.js:912:25](http://127.0.0.1:8000/scripts/world-info.js)
Sorted 0 world lore entries using strategy 1 [world-info.js:925:17](http://127.0.0.1:8000/scripts/world-info.js)
Invalid URI. Load of media resource  failed. [127.0.0.1:8000](http://127.0.0.1:8000/)
calling runGenerate [script.js:2532:17](http://127.0.0.1:8000/script.js)
generating prompt [script.js:2561:25](http://127.0.0.1:8000/script.js)
---calling setPromtString 0 [script.js:2710:25](http://127.0.0.1:8000/script.js)
--setting Prompt string [script.js:2616:25](http://127.0.0.1:8000/script.js)
No prompt bias was found. [script.js:2662:33](http://127.0.0.1:8000/script.js)
rungenerate calling API [script.js:2807:21](http://127.0.0.1:8000/script.js)
pushed prompt bits to itemizedPrompts array. Length is now: 3 [script.js:2844:21](http://127.0.0.1:8000/script.js)
Event emitted: message_received [eventemitter.js:52:13](http://127.0.0.1:8000/scripts/eventemitter.js)
```

**Desktop (please complete the following information):**
 - OS/Device: Windows 11
 - Environment: local
 - Node.js version (if applicable): v18.17.0
 - Browser: Firefox
 - Generation API: NovelAI
 - Branch: staging
 - Model: Kayra

**Additional context**
You can check their latest blog post for more information https://blog.novelai.net/kayra-for-all-novelai-subscription-tiers-free-trial-clio-8k-context-for-all-tiers-33aa933f3aad

**Comment by ghost** [comment]
This is already fixed in the `staging` branch, I think, as the NovelAI API now gets used for determining the context sizes. Care to check if this works for you?

**Comment by minipasila** [comment]
> This is already fixed in the `staging` branch, I think, as the NovelAI API now gets used for determining the context sizes. Care to check if this works for you?

I updated to the latest version of staging branch and the issue still persists.

**Comment by ghost** [comment]
> I updated to the latest version of staging branch and the issue still persists.

Thank you, but can you please try a fresh cloned `staging` branch installed in different folder and test from a default "baseline" with just your API key added? There are too many variables that could interfere otherwise.

**Comment by Cohee1207** [comment]
The problem is actually the opposite: there is no hard code, but I can't get this info from the API. staging branch calls https://api.novelai.net/user/subscription to get the max allowed context size per subscription. And it is not split per model. I'll try to get in touch with NovelAI developers.

**Comment by Cohee1207** [comment]
Meanwhile I hardcoded context values according to your comment

**Comment by minipasila** [comment]
> Meanwhile I hardcoded context values according to your comment

Yeah it works now, thanks.
